# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DockerCredentialMagic < Formula
  desc "A magic shim for Docker credential helpers 🪄"
  homepage "https://github.com/docker-credential-magic/docker-credential-magic"
  version "0.9.0"
  license "Apache License"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/developer-guy/docker-credential-magic/releases/download/v0.9.0/docker-credential-magic_Darwin_arm64.tar.gz"
      sha256 "fa6fcb8258f33df318e7fc9f8dd81d65820665ae4d348e8347fa7c41cf244d81"

      def install
        bin.install "docker-credential-magic"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/developer-guy/docker-credential-magic/releases/download/v0.9.0/docker-credential-magic_Darwin_x86_64.tar.gz"
      sha256 "338390dbb200b61115850a7d772efe26decd3c86e08e7941abb8703b1bc0aafe"

      def install
        bin.install "docker-credential-magic"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/developer-guy/docker-credential-magic/releases/download/v0.9.0/docker-credential-magic_Linux_armv6.tar.gz"
      sha256 "4217e511334f2143b60822978c0af504040bafe4930e63012d367c70f5678e35"

      def install
        bin.install "docker-credential-magic"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/developer-guy/docker-credential-magic/releases/download/v0.9.0/docker-credential-magic_Linux_arm64.tar.gz"
      sha256 "eb03a1c5bcd34b88bf8ef859b68c37cbc040cf69be39bff387ff58ebf7eb1161"

      def install
        bin.install "docker-credential-magic"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/developer-guy/docker-credential-magic/releases/download/v0.9.0/docker-credential-magic_Linux_x86_64.tar.gz"
      sha256 "714bedf04a89548a0dcef09f033c4e7c07527b42778dc1f2fa9299562b3ba0b7"

      def install
        bin.install "docker-credential-magic"
      end
    end
  end

  depends_on "go" => :optional
  depends_on "git"

  test do
    system "#{bin}/docker-credential-magic version"
  end
end
