# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scorecard < Formula
  desc "Security Scorecards - Security health metrics for Open Source"
  homepage "https://openssf.org"
  version "3.2.1"
  license "Apache License"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/developer-guy/scorecard/releases/download/v3.2.1/scorecard_3.2.1_darwin_arm64.tar.gz"
      sha256 "4f1004d76c2fe864c192573fb63b85edeb436e8795f169fed8d9988cbcbe2ecd"

      def install
        bin.install "scorecard"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/developer-guy/scorecard/releases/download/v3.2.1/scorecard_3.2.1_darwin_amd64.tar.gz"
      sha256 "617ba3806a16d859cdcaef82c0ea6a0dbb568474962fcfc01db4300053234421"

      def install
        bin.install "scorecard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/developer-guy/scorecard/releases/download/v3.2.1/scorecard_3.2.1_linux_arm64.tar.gz"
      sha256 "2fc9f87e870b363a579318a277bc80e279785894fc949b41282540a5bbbf9f1c"

      def install
        bin.install "scorecard"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/developer-guy/scorecard/releases/download/v3.2.1/scorecard_3.2.1_linux_armv6.tar.gz"
      sha256 "9e56cc96ba2dfe78b124302af1bf43b1c1ac4f4d76fc8a4693a040ede20ff19a"

      def install
        bin.install "scorecard"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/developer-guy/scorecard/releases/download/v3.2.1/scorecard_3.2.1_linux_amd64.tar.gz"
      sha256 "a5d953d77cb3b2782829f8cf9ea2797a68e4ca1c3884186e8dcfb8ced25e6282"

      def install
        bin.install "scorecard"
      end
    end
  end

  depends_on "go" => :optional
  depends_on "git"

  test do
    system "#{bin}/scorecard version"
  end
end
